import Foundation

enum TimelineShareText {
    static func summary(
        pet: PetProfile,
        destination: Destination,
        departure: Date,
        items: [TimelineItem]
    ) -> String {
        let dateStyle = Date.FormatStyle.dateTime.month(.abbreviated).day().year()
        var lines: [String] = []
        lines.append("\(pet.name) → \(destination.name)")
        lines.append("Departure: \(departure.formatted(dateStyle))")
        lines.append("")
        lines.append("Compliance Timeline")
        lines.append(String(repeating: "—", count: 20))
        for item in items {
            lines.append("\(item.dueBy.formatted(dateStyle)) — \(item.title)")
            if !item.detail.isEmpty {
                lines.append("    \(item.detail)")
            }
        }
        lines.append("")
        lines.append("Generated by My Pet Passport. Informational only — confirm requirements with your vet.")
        return lines.joined(separator: "\n")
    }
}
